name = "espidf_gnat_runtime_acats_bundle_1"
description = "ESPIDF GNAT Runtime ACATS bundle #1"
version = "0.2.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = []

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_base = "*"
a0b_tools = "*"
espidf_gnat_runtime = "*"
gnat_xtensa_esp32_elf = "^15"
xtensa_dynconfig = "*"

[[actions]]
type = "pre-build"
command = ["a0b-runtime",
           "--bb-runtimes=../../../crates/bb-runtimes/",
           "--svd=../../../crates/espidf_gnat_runtime/svd/esp32s3.svd",
           "--runtime-description=../../../crates/espidf_gnat_runtime/runtime-esp32s3.json",
           "--no-startup"]

[[pins]]
a0b_tools = { path='../../../crates/a0b-tools' }
espidf_gnat_runtime = { path='../../..' }
xtensa_dynconfig = { path='../../../crates/xtensa-dynconfig' }
